### ISSUE TITLE
[1.9] A deployed agent cannot reach its owner when nobody is connected

### ISSUE THREAD

**Issue by wu-changxing** [openonion/connectonion#843]
## What happens

An agent running anywhere except an attached terminal has **no way to reach a human**. When it calls `ask_user`, it gets a string back saying nobody answered, and the run ends with the question unanswered.

`connectonion/useful_tools/ask_user.py` says so in its own comment:

```python
if not agent.io:
    # One-shot mode (co ai "prompt", and every deployed agent) has nobody to
    # answer.
```

`agent.io` is a WebSocket (`connectonion/network/io/websocket.py`, assigned at `http_router.py:48`), so a human has to be **connected at that moment** for the question to go anywhere. That covers exactly one situation: someone sitting in front of an open session. It does not cover `co ai "prompt"`, cron runs, or any deployed agent.

The current behaviour is correct as far as it goes — #553 and #535 established that an unanswered question must not read as approval, and the returned string says so explicitly. The gap is not that it answers wrongly. **It is that there is no channel at all.**

## Who this affects

Every unattended run, which is most of them:

- `co ai "prompt"` one-shots — no `io` by construction
- Scheduled/cron agents — nobody is watching at 3am
- Deployed agents — the situation the comment names

Concretely: the run in #837 built an entire event listing across five ticketing platforms, then hit a verification step it could not pass alone and stopped. Account created, organiser page built, form complete, and no way to say *"I need six digits, send them to me."* A human was awake and willing. There was no path from the agent to that human.

## The channel that already exists

Email needs nothing bought and no new dependency. All three parts are in the repo today:

- `send_email` — the agent sends from its own address ✅
- `get_emails` / `mark_read` — the agent reads its own inbox ✅
- `ask_user`'s existing `fields` contract already supports structured input including `type: "password"` — "paste the code here" is already expressible ✅

Every agent already has an address (`0x{10}@mail.openonion.ai`, Cloudflare inbound → webhook → DB), and it costs nothing because we own the domain.

So the flow **agent gets stuck → emails the owner → owner replies → agent reads the reply → continues** is buildable with zero purchases.

Implementation for this half is written and passing on branch `feat/ask-user-email-fallback`: `ask_user` falls back to emailing `OWNER_EMAIL`, polls the agent's own inbox for a reply, strips the quoted question, and on timeout or missing config returns the same not-approval string as today with the reason appended. 5 new unit tests, no new dependencies.

## What email does not give you: attention

Email is asynchronous. Nobody is watching an inbox at 3am. A run that stops at midnight and mails a question gets its answer at 9am — by which time the run is long dead.

**A phone call or SMS is the only channel that interrupts a human who is not looking.** That is its whole value here, and it is a real one — but it is an escalation on top of the email path, not a replacement for it. The reply can still come back by email.

Provider selection for that escalation is decided in #359 (Twilio, one shared outbound number, ~$3–8/month total, AU rates verified). This is deliberately **outbound-only**, which is what keeps it clear of everything #837 documented — those blockers are all on the inbound/OTP side.

## Scope

1. **Email fallback** (branch exists) — `ask_user` reaches the owner by email when there is no `io`, waits, returns the reply
2. **Urgent escalation** — an urgent question additionally rings or texts the owner; the answer still comes back by email
3. Not in scope: SMS as an inbound reply channel (that is #358), live voice conversation (that is #359)

## Definition of done

- An agent with no `io` can ask a question, get an answer from a human, and continue — proven end-to-end on a real deployed agent, not only in unit tests
- A question that is never answered still returns the not-approval string, with the reason (no owner configured / send failed / timed out) — the guarantee from #553/#535 must not regress
- Where the owner's address comes from is documented; today nothing in `.co/` records who the human is

## Related

- #837 — why the agent cannot instead have a number of its own for receiving verification codes (the research stands; see its repositioning comment)
- #359 — the phone channel design and the provider decision for the escalation
- #358 — SMS as an inbound channel, separate build
- #553 / #535 — established that unanswered must never read as approval

**Comment by wu-changxing** [comment]
## Separating out a gap this issue exposes but does not own

Building the email fallback surfaced something more basic than "we need an address to mail":

**Nothing records who an agent belongs to.** Not `.co/config.toml` (framework version, model, max_iterations — nothing about a person), not `.co/agent.json` (address, alias, bio, skills — the agent's own identity, not its owner's), and not the backend: oo-api keys accounts on the public key and returns balance and timestamps, no owner email (`auth/routes.py`, `GET /api/v1/auth/me`).

The email fallback needs this, so it uses an `OWNER_EMAIL` environment variable — matching how `AGENT_EMAIL` already works, and the smallest thing that works. **That is a placeholder, and worth naming as one now, because env vars become de facto standards quietly and then cost a migration to change.**

The reason this is bigger than one config value: an agent that does not know who it belongs to cannot answer several questions it will eventually be asked.

- *Who do I ask?* — this issue
- *Whose instructions do I trust?* — the trust layer resolves what an address is allowed to do, but never who the agent is acting for
- *Who gets the result?* — a deployed agent finishing work has no addressee
- *Who do I alarm?* — the same gap as the above, in the failure direction

Questions worth answering deliberately rather than by default:

1. Should owner identity be a first-class agent concept (its own file or a block in `.co/`) rather than an environment variable?
2. Should the backend hold it? It already authenticates the account; it just does not know the human behind the key. Storing it there makes it survive a machine, but puts a personal email in the account record.
3. What happens with more than one owner — a team agent, or an agent that gets handed over?
4. Is "owner" even the right primitive, or is it "who to contact", which might be several addresses with different urgency (email for questions, phone for emergencies — see #359)?

**Not blocking the email fallback** — `OWNER_EMAIL` is fine for v1 and the PR ships with it. This is flagged so the decision gets made on purpose. Happy to split it into its own issue if that is the preferred home.

**Comment by wu-changxing** [comment]
## The plan, and where every related issue sits in it

This issue is the umbrella: **an agent that gets stuck must be able to reach a human.** Everything else in this area is either a channel for doing that, or a record of a channel we investigated and rejected. Putting the map in one place so the pieces stop reading as separate ideas.

The problem decomposes into two questions that are easy to conflate:

- **How does the question get to a human?** → a channel. Several exist, they differ in cost and in whether they can interrupt someone.
- **How does the answer get back?** → email, for all of them, in every stage below. Nothing else is needed and nothing else is planned.

### Stage 1 — email · no purchase, no new dependency · PR #844 (draft, CI green)

`ask_user` falls back to emailing the owner and polling the agent's own inbox. Three parts already existed (`send_email`, `get_emails`/`mark_read`, and `ask_user`'s `fields` contract); every agent already has an address because we own the domain.

This is the floor: after it lands, no agent dies silently on a question. What it cannot do is wake anyone — a run that stops at midnight gets its answer at 9am.

### Stage 2 — attention

Email carries the question. What it lacks is the ability to interrupt someone who is not looking. Three ways to add that, and they are not competing — they serve different audiences:

| channel | cost | needs | interrupts? | who it is for |
|---|---|---|---|---|
| **Telegram bot** (#352) | free | recipient has Telegram | yes, push | **us, today** |
| own push (FCM → oo-chat-android) | free | recipient installs our app; FCM project + token registration, none of which exists yet | yes, push | our users, later |
| **SMS / voice** (`openonion/oo-api#135`) | ~$0.05/msg, ~$0.075/min, $3–8/mo number | recipient has a phone | **yes, and through Do Not Disturb** | **customers** |

**Telegram is the cheapest path to "wake Aaron at 3am" and #352 is already filed for it.** Phone is the one that survives contact with a customer who has not installed anything and is not in our Discord — and voice is the only channel that rings through silence. They are sequential, not alternatives: Telegram first because it is free and buildable now, phone because it is the product capability.

Phone lives in **oo-api, not the framework** — the same shape as email, for the same reason: if the framework talked to the carrier directly, every deployed agent would carry a credential that can place international calls on our bill. Provider is **Telnyx** (Aaron's call; see `openonion/oo-api#135` for the reasoning and the two things to watch).

### Stage 3 — verification code relay

The original blocker in #837: a human receives a code on their own phone and passes it to the agent. With stages 1 and 2 in place this is just a `fields` question over an existing channel — the human is in the loop for ten seconds instead of the run dying.

## Related issues, and what each one is

| issue | what it is | status |
|---|---|---|
| **#843** (this) | umbrella: the agent cannot reach a human | open |
| **PR #844** | stage 1, email fallback | draft, CI 11/11 green |
| **#837** | research record: why an agent *cannot* have a number for **receiving** verification codes — Twilio's 30038 filter, four AUPs, NANP VoIP classification, bulk-purchase heuristics | open, narrowed to one cheap unanswered test |
| **#359** | the phone channel design + provider comparison + AU compliance + billing + porting + MVNO | open, provider decided |
| **#352** | Telegram as a channel — the cheapest attention today | open, unstarted |
| **#358** | SMS as an **inbound** channel | open — deliberately **not** in this plan; answers come back by email |
| **`openonion/oo-api#135`** | the phone endpoint, credentials server-side, Telnyx | open |

## The distinction that makes all of this work

#837 established that an agent cannot have a number for **receiving** verification codes. Everything in this plan is about **outbound** — the agent reaching out. Those are different problems with different regulatory surfaces, and conflating them is what made the original issue unbuildable.

The identity number stays the human's own real mobile. Nothing is bought for it, and it must never be ported into a CPaaS — that would convert the one property that makes it work into the exact thing the filters in #837 reject.

## Still needs a decision

1. **Is the urgent channel a notification or a conversation?** A spoken notification is a few lines; a conversation needs the latency work in #359. My read: notification is enough — phone's value here is attention, not information.
2. **Where does owner identity live?** `OWNER_EMAIL` ships in PR #844 as a placeholder. Nothing records who an agent belongs to — not `.co/`, not the backend. Details in the comment above; the sharpest version is whether "owner" is even the right primitive, or whether it should be "who to contact", plural, with different urgency per channel. Phone makes that concrete because email and phone are its first two entries.

**Comment by wu-changxing** [comment]
Best-practice review for PR #844: sender plus arrival time is not a sufficient authorization correlation. The first implementation could treat an unrelated owner email as the answer, and two simultaneous questions could cross. Commit 7a9afb9c now assigns each question a fresh high-entropy CO-ASK subject tag and requires both owner and tag to match. Inbox outages and empty replies fail closed. OWNER_EMAIL can remain the documented v1 contact source if we state that it is a contact route, not proof of protocol authority; the issue should remain open until the real deployed-agent end-to-end acceptance test passes.

**Comment by wu-changxing** [comment]
## Merge-readiness review for PR #844

PR #844 remains Draft despite CI 11/11 green. The high-entropy request tag correctly closes unrelated/concurrent-reply correlation, and unanswered paths fail closed, but the best-practice review found merge blockers:

1. Email fallback must reject `password`/secret fields or first define a secret channel and retention/redaction policy; inbound email bodies are persisted unchanged.
2. `OWNER_EMAIL` is a contact route, not yet an authenticated approval identity. Project `.env` currently overrides the global keys file, so the authority and precedence decision must be explicit and tested.
3. The framework calls the generated body plain text, while oo-api sends it to Resend as HTML. Question/options/field labels therefore require HTML escaping and subject control-character handling.
4. The 15-minute synchronous wait needs opt-in/configuration/cancellation; the 20-message window needs a cursor or server-side tag query; concurrent calls need a pending-request/rate-limit policy.
5. The issue's required real deployed-agent end-to-end acceptance test is still outstanding.

The detailed findings have been posted as a review on #844. Do not promote or merge the PR until these are closed.

**Comment by wu-changxing** [comment]
## Safe v1 contract after the merge-readiness review

The implementation should preserve the accepted no-IO and approval decisions instead of making `OWNER_EMAIL` silently authoritative:

1. **Default remains immediate fail-closed.** Email fallback is used only when an operator explicitly enables it (proposed `CONNECTONION_ASK_USER_EMAIL=1`). Merely setting an address must not turn every one-shot/library call into a 15-minute outward side effect.
2. **Contact replies do not replace protocol approval.** `OWNER_EMAIL` identifies the configured decision contact for an ordinary `ask_user` question. It cannot satisfy Host/ACP `session/request_permission`, grant a tool permission, or bypass the existing admin/request/session binding in DD-030/DD-037. Global `~/.co/keys.env` owner configuration must win over a conflicting project `.env`; a deployed application may provide the value directly in its process environment.
3. **No secrets over the persistent mailbox.** Password, secret, token, OTP, and one-time-code fields fail closed before sending. A future secret relay needs its own retention/redaction design and backend support; field types must not quietly downgrade into ordinary email text.
4. **Treat the backend body as HTML.** Escape question, options, and labels into a small safe wrapper; remove CR/LF/control characters from the subject; add hostile-input regressions.
5. **Query by the high-entropy request tag.** Add an authenticated oo-api inbox filter for the exact `CO-ASK` subject token and have the framework use it. Increasing a fixed recent-message window is not a cursor and still loses the answer in a busy inbox.
6. **Bound and interrupt the wait.** Make timeout/polling configuration bounded, check cancellation during sleeps, permit only one pending email ask per agent/contact, and add a cooldown so repeated tool calls cannot create an outbound-email burst.
7. **Acceptance remains real E2E.** Unit/CI success is necessary but promotion waits for a deployed agent sending the escaped question, receiving only the correlated reply through the filtered endpoint, respecting cancellation/timeout, and leaving every rejected path as `NOT ANSWERED`.

This splits cleanly into an oo-api filtering PR and the existing framework PR #844. Both stay Draft until the deployed end-to-end gate passes.

**Comment by wu-changxing** [comment]
The security redesign is implemented on Draft PR #844 at exact head `22e2fedb`.

The implementation now follows DD-043:

- no-IO remains immediate/fail-closed by default; email requires explicit opt-in
- email cannot grant Host/ACP permission
- persistent email accepts only bounded non-sensitive choices, encoded as numeric reply IDs; fields and arbitrary reply text are rejected
- common secret/OTP/token shapes are blocked before send, with the caller contract documented as the primary boundary
- HTML and subject/header data are sanitized
- owner lookup, cancellation, timeout, per-owner pending/cooldown, sender/tag correlation, and old-backend capability checks are bounded and fail closed
- oo-api #140 filters before `LIMIT` and proves the exact applied filter

Evidence on the exact framework head:

- focused suite: 88 passed
- full locked unit suite excluding only the cross-repository docs version assertion: 6535 passed, 13 skipped, 13 deselected
- locked ACP/MCP stdio file: 25 passed
- Ruff, compileall, and diff check: passed
- final independent review: 0 P0/P1/P2 findings
- remote matrix/Windows/CodeQL: running

The separate docs version check is explicit: 6 passed, 1 failed because the local docs-site checkout says 1.6.0 while this branch says 1.7.0a1.

This issue and PR remain open/Draft. Remaining work is owner review, green remote checks, deployment of oo-api #140, and a real authenticated send/reply/cancel/mark-read round trip. No merge or release should happen before that.

**Comment by wu-changxing** [comment]
Remote verification has finished on exact framework head `22e2fedb`: every check passed.

- Linux full matrix: Python 3.10, 3.11, 3.12, 3.13
- Windows browser matrix: Python 3.10, 3.12, 3.13
- Windows full E2E
- lockfile
- Python static analysis and CodeQL

PR #844 remains Draft because the remaining gate is integration, not unit/CI quality: deploy oo-api #140 and run the real authenticated email round trip before merge.

**Comment by wu-changxing** [comment]
Backend prerequisite openonion/oo-api#140 has now been squash-merged after green CI and final 0-findings review. Main commit: `d329cc98`.

This did **not** deploy production: the oo-api workflow deploys only from a `v*` tag or an explicit `workflow_dispatch`; ordinary merges to `main` only run tests. Framework PR #844 therefore remains Draft. Next gate is a separately reviewed deployment of `d329cc98`, followed by the real authenticated email round trip.

**Comment by wu-changxing** [comment]
## Owner identity: three concrete options, so this can be decided rather than deferred

I raised this abstractly twice and got no decision, which was my fault — "is owner the right primitive" is not answerable in a sentence. Here are three shapes to pick between.

**The three things an agent needs a person for.** The third does not exist today at all:

| | today |
|---|---|
| ① it is stuck and needs an answer | email (#844) |
| ② something is wrong and someone must look now | phone / Telegram (#926, #866) |
| ③ **it finished and the result goes to…** | **nothing** |

### A — keep `owner`, add a column per channel

```
users.owner_email / owner_phone / owner_telegram   (+ each *_set_at)
```

| | |
|---|---|
| ① | `owner_email` |
| ② | `owner_phone` or `owner_telegram`, **priority hard-coded** |
| ③ | `owner_email` |
| more than one owner | **not supported.** Handing an agent to a customer means overwriting the field and losing contact, or a second account |
| migration | **~zero** — this is already the shape |
| gives up | urgency lives in code, not data; has to be redone when agents are delivered to customers |

### B — a contact list: one owner, several channels, ordered by urgency

```
contacts(public_key, channel, value, urgency, set_at)
```

| | |
|---|---|
| ① | lowest-urgency channel available |
| ② | highest |
| ③ | the default channel |
| more than one owner | **still not supported** |
| migration | two columns become a table; `OWNER_EMAIL` becomes "first entry" |
| gives up | pays for a table without buying multi-owner — still needs redoing later |

### C — who to contact, by role

```
contacts(public_key, role, channel, value, set_at)
role ∈ {asks, alerts, results}      one role may have several people
```

| | |
|---|---|
| ① | `asks` |
| ② | `alerts` |
| ③ | `results` |
| more than one owner | **native.** Delivered to a customer: asks/alerts → them, results → them and us |
| migration | largest — **and cheapest right now**, while #844, #926 and `openonion/oo-api#136` are all still drafts |
| gives up | a table and a concept to explain on day one; a real YAGNI risk |

### The question that actually decides it

**Will we hand agents to customers who then own them?**

- **No, or not within a year → A.** Least machinery, and the placeholder already in the drafts becomes the answer.
- **Yes, and soon → C.** Going A→C later means migrating two *published* contracts (`OWNER_EMAIL` in the framework, columns in the backend). Doing it now only touches drafts.

**B is not recommended** — it pays a table's cost without buying multi-owner, so it still needs a second migration.

Leaning A, on the grounds that building for an unbuilt product is the thing we usually regret. But if agents-delivered-to-customers is near, this is the cheapest hour it will ever cost.

**Comment by wu-changxing** [comment]
Adding the third channel to the map above: **#938 (`co voice`)** — the agent phones you, talks it through, and comes back with a decision.

The line through all of it:

| | carries | built |
|---|---|---|
| email (#844) | the question, and the answer | draft, CI green |
| Telegram (#866) | attention, free | **merged** |
| SMS / voice notification (#926, `openonion/oo-api#136`) | attention, through a silent phone | draft |
| **voice conversation (#938)** | **a decision** | design only |

The first three all end the same way: a human goes and reads something. #938 is the case where the answer is a judgement call and typing it out is the expensive part — the agent explains, you talk, and what you said comes back as something it can act on.

`no_answer` is treated as loudly as a rejection there, which is the rule this line of work has kept returning to since #553: **unanswered is never yes.**
